import type { TokenSet } from "../export-tokens.js";
import type { BrandConfig } from "../types.js";
import {
  deriveFacts,
  frontmatter,
  padRight,
  resolvePx,
  type SkillArtifact,
  skillFile,
} from "./types.js";

const NAME = "tokens-and-theming";

const DESCRIPTION = `Use when authoring or reviewing UI that consumes this Lattice-generated token system — choosing semantic tokens, spacing, type roles, or light/dark theme swapping.
Not for inventing new color ramps, generating tokens from scratch, icon motion, or general CSS unrelated to these tokens.`;

export function buildTokensSkill(
  config: BrandConfig,
  set: TokenSet
): SkillArtifact {
  const f = deriveFacts(config, set);
  const supportingLine =
    f.supportingHues.length > 0
      ? f.supportingHues.map((h) => `\`${h}\``).join(", ")
      : "_(none — primary hue covers all accent roles)_";

  const spaceRows = [
    ["--space-xs", "--dimension-50", "--space-xs"],
    ["--space-sm", "--dimension-100", "--space-sm"],
    ["--space-md", "--dimension-150", "--space-md"],
    ["--space-lg", "--dimension-200", "--space-lg"],
    ["--space-xl", "--dimension-300", "--space-xl"],
    ["--space-2xl", "--dimension-400", "--space-2xl"],
    ["--space-3xl", "--dimension-500", "--space-3xl"],
    ["--space-4xl", "--dimension-600", "--space-4xl"],
    ["--space-5xl", "--dimension-800", "--space-5xl"],
    ["--space-6xl", "--dimension-1000", "--space-6xl"],
  ] as const;
  const spaceTable = spaceRows
    .map(
      ([sem, prim, ref]) =>
        `${padRight(sem, 11)} → ${padRight(prim, 18)} (${resolvePx(set.light, ref)})`
    )
    .join("\n");

  return {
    description: DESCRIPTION.replace(/\n/g, " ").trim(),
    files: [
      skillFile(
        "SKILL.md",
        `${frontmatter(NAME, DESCRIPTION)}
# Tokens & theming

This design system was generated by [Sora Lattice](https://lattice.soralabs.io.vn). It ships **${f.tokenCount}** CSS custom properties (primitive + semantic). **Always reach for the semantic token first** — it survives theme swaps and config regenerations.

**Core principle:** tokens own values; components own structure. Never hard-code \`px\` / \`rem\` / hex in component CSS when a token exists.

## The four gates

1. **Semantic first** — primitive (\`--color-<hue>-<step>\`, \`--dimension-*\`) only when no semantic fits.
2. **Pair by role** — \`foreground/onX\` with matching \`background/X\`; never cross-pair.
3. **Density via tokens** — use \`--space-*\` / \`--shape-radius-*\`; do not read density at runtime.
4. **Theme via selector** — dark is \`data-theme="dark"\` on an ancestor, not a media-query fork of every rule.

## Brand snapshot

- Primary hue: \`${f.primaryHueName}\` (OKLCH ≈ ${f.primaryHueAngle.toFixed(1)}°)
- Supporting hues: ${supportingLine}
- Neutral tint: \`${config.neutralTint}\` · Density: **${config.density}** (\`--dimension-100\` = ${f.densityBase}) · Roundness: **${config.roundness}** · Shadows: **${config.shadows}**

## Read next

| Situation | Open |
| --- | --- |
| Which token for bg / text / border / space / type | [references/DECISION-TREE.md](references/DECISION-TREE.md) |
| Elevation, identity, modifiers mental model | [references/ARCHITECTURE.md](references/ARCHITECTURE.md) |
| Spacing ladder, type, radius, shadow | [references/SCALES.md](references/SCALES.md) |
| Light/dark, subtree themes, \`@layer\` | [references/THEMING.md](references/THEMING.md) |

## Procedure

1. Open the decision tree; pick the semantic token for the role.
2. If building layout, prefer \`--space-*\` over \`--dimension-*\`.
3. For dark mode, toggle \`data-theme\` — do not duplicate token names.
4. Escape hatches only inside \`@layer lattice.overrides\` (see THEMING).

## When to break the rules

- Hard-coded colors: SVG artwork whose identity *is* the color.
- Hard-coded sizes: one-off structural measurements (e.g. 1px hairline).
- \`!important\` on tokens: never — use \`lattice.overrides\`.
`
      ),
      skillFile(
        "references/ARCHITECTURE.md",
        `# Token architecture

Three mental models — **elevation**, **identity**, and **modifiers** — wired by semantic aliases.

## Backgrounds

Elevation is opaque: \`sunken\` → \`base\` → \`raised\` → \`overlay\`.

Identity surfaces (\`primary\`, \`accent\`, \`success\`, \`warning\`, \`critical\`, \`info\`) carry meaning, not elevation.

## Foregrounds

- \`foreground/onBase\`, \`foreground/onBaseMuted\` — body text on elevation surfaces.
- \`foreground/onPrimary\`, \`foreground/onAccent\`, \`foreground/onCritical\`, … — text on identity surfaces. Always pair with the matching background.
- \`foreground/primary\`, \`foreground/accent\` — saturated brand accents/links, **not** body copy.

## Modifiers

\`*Subtle\` backgrounds (e.g. \`background/primarySubtle\`) are desaturated lightness shifts — never alpha. \`foreground/onBaseMuted\` is reduced contrast via lightness, not opacity.

Primitive ramps look like \`--color-<hue>-<step>\` (e.g. \`--color-${f.primaryHueName.toLowerCase()}-500\`).
`
      ),
      skillFile(
        "references/DECISION-TREE.md",
        `# Decision tree: which token?

\`\`\`
Need a color?
├── Background of a region?
│   ├── Default page surface          → ${f.bgBase}
│   ├── Card / elevated surface       → ${f.bgRaised}
│   ├── Modal / popover               → ${f.bgOverlay}
│   ├── Recessed / muted area         → ${f.bgSunken}
│   ├── Brand emphasis (CTA)          → ${f.bgPrimary}
│   └── Status surface                → --color-background-{success|warning|critical|info}
│
├── Text?
│   ├── Body copy                     → ${f.fgOnBase}
│   ├── Secondary / muted             → ${f.fgMuted}
│   ├── Accented text or link         → ${f.fgPrimary}
│   ├── On a primary surface          → ${f.fgOnPri}
│   └── On a status surface           → --color-foreground-on{Success|Warning|Critical|Info}
│
└── Border / divider?                 → ${f.borderTok} (or --color-border-strong)

Need a size?
├── Padding / gap / margin            → --space-* (semantic, t-shirt scale)
├── Structural measurement            → --dimension-* (primitive, fixed px ladder)
├── Corner radius                     → --shape-radius-{container|action|field|badge|max}
└── Stroke width                      → --shape-border-{thin|regular|thick}

Need a type style?
├── Marketing/section title           → --font-heading-{xs..4xl}-size + --font-heading-weight
├── Body copy                         → --font-body-md-size + --font-body-weight-regular
├── Button / tab label                → --font-action-{xs..lg}-size + --font-action-weight
└── Input text                        → --font-field-{xs..lg}-size + --font-field-weight
\`\`\`
`
      ),
      skillFile(
        "references/SCALES.md",
        `# Spacing, shape, typography

## Spacing

Density is **${config.density}** (\`--dimension-100\` = ${f.densityBase}). Other dimension steps are multiples — changing density rescales space, radius, and control size together.

\`\`\`
${spaceTable}
\`\`\`

**Rule:** \`--space-*\` for padding/gap/margin. \`--dimension-*\` only for structural measurements. Never raw \`px\` / \`rem\` in component CSS.

## Shape & shadow

- Radii: \`--shape-radius-{container, subcontainer, supercontainer, action, field, badge, max}\` (roundness: **${config.roundness}**).
- Borders: \`--shape-border-{thin, regular, thick}\`.
- Shadows (preset **${config.shadows}**): \`--shadow-{xs, sm, md, lg, xl}\`.

## Typography

- Ladder: \`--typography-size-{100..800}\`.
- Weights: \`--typography-weight-{300..900}\` (only weights fonts use).
- Families: \`--typography-font-family-body\`, \`--typography-font-family-heading\`.
- Roles: \`heading\`, \`body\`, \`action\`, \`field\` — pick role first, then size.

\`\`\`css
.page-title {
  font-family: var(--font-heading-family);
  font-size:   var(--font-heading-2xl-size);   /* ≈ ${f.heading2xl} */
  font-weight: var(--font-heading-weight);
  line-height: var(--font-heading-lineheight);
}

.body-copy {
  font-family: var(--font-body-family);
  font-size:   var(--font-body-md-size);       /* ≈ ${f.bodyMd} */
  font-weight: var(--font-body-weight-regular);
  line-height: var(--font-body-lineheight);
}
\`\`\`
`
      ),
      skillFile(
        "references/THEMING.md",
        `# Theme swapping & cascade

Light is default. Dark activates with \`data-theme="dark"\` on \`:root\` (or any ancestor):

\`\`\`html
<html data-theme="dark">…</html>
\`\`\`

The CSS export emits \`:root[data-theme="dark"] { … }\` with only the *diff* from light.

\`\`\`ts
const stored = localStorage.getItem('theme');
const initial = stored ?? (matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
document.documentElement.dataset.theme = initial;

function setTheme(t: 'light' | 'dark') {
  document.documentElement.dataset.theme = t;
  localStorage.setItem('theme', t);
}
\`\`\`

### Subtree themes

\`\`\`html
<main>
  <article data-theme="dark">Always dark inside a light page</article>
</main>
\`\`\`

## CSS cascade layers

\`\`\`css
@layer lattice.base, lattice.theme, lattice.overrides;
\`\`\`

- \`base\` — element defaults.
- \`theme\` — generated tokens.
- \`overrides\` — app customizations (escape hatch).

Put app-level token edits in \`@layer lattice.overrides\`.
`
      ),
    ],
    id: "tokens",
    name: NAME,
    rootDir: `skills/${NAME}`,
    title: "Tokens & theming",
  };
}
